# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-02 07:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('YYblog', '0002_auto_20170702_1502'),
    ]

    operations = [
        migrations.CreateModel(
            name='collectPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('post_id', models.IntegerField()),
                ('collect_time', models.DateTimeField()),
            ],
            options={
                'ordering': ['-collect_time'],
            },
        ),
    ]
