# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-03 03:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('YYblog', '0003_collectpost'),
    ]

    operations = [
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('follow_id', models.IntegerField()),
                ('followed_id', models.IntegerField()),
                ('follow_time', models.DateTimeField()),
            ],
            options={
                'ordering': ['-follow_time'],
            },
        ),
    ]
