# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-05 14:04
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('YYblog', '0005_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatePost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('post_id', models.IntegerField()),
                ('like', models.IntegerField(default=0)),
                ('create_time', models.DateTimeField(default=datetime.datetime(2017, 7, 5, 22, 4, 8, 690579))),
            ],
        ),
    ]
