# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-06 02:26
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('YYblog', '0006_statepost'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='head_photo',
            field=models.ImageField(default='head_photos/no_image.jpg', upload_to='head_photos/'),
        ),
        migrations.AlterField(
            model_name='statepost',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2017, 7, 6, 10, 26, 44, 98228)),
        ),
    ]
