# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-07 03:15
from __future__ import unicode_literals

import ckeditor.fields
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('YYblog', '0012_auto_20170706_1207'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='标题')),
                ('content', ckeditor.fields.RichTextField(verbose_name='正文')),
            ],
        ),
        migrations.AlterField(
            model_name='statepost',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2017, 7, 7, 11, 15, 49, 251634)),
        ),
    ]
