# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-07 03:29
from __future__ import unicode_literals

import ckeditor.fields
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('YYblog', '0013_auto_20170707_1115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='body',
            field=ckeditor.fields.RichTextField(verbose_name='正文'),
        ),
        migrations.AlterField(
            model_name='statepost',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2017, 7, 7, 11, 29, 49, 388188)),
        ),
    ]
